"""add available_copies to books

Revision ID: cbe2a193ab6b
Revises: 90e10eb9c640
Create Date: 2025-11-06 11:06:48.313663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe2a193ab6b'
down_revision: Union[str, Sequence[str], None] = '90e10eb9c640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable
    op.add_column('books', sa.Column('available_copies', sa.Integer(), nullable=True))

    # 2. Update available_copies based on quantity minus borrowed count
    op.execute("""
        UPDATE books
        SET available_copies = quantity - (
            SELECT COUNT(*)
            FROM borrows
            WHERE borrows.book_id = books.id
        )
    """)

    # 3. Make the column NOT NULL
    op.alter_column('books', 'available_copies', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'available_copies')
    # ### end Alembic commands ###
